from typing import Any, Iterator

BACKEND: str
PRIVATE_VERSION: str

def emulation_headers(value: Any) -> list[tuple[list[int], list[int]]]: ...

class NativeResponse:
    status: int
    version: str
    headers: list[tuple[list[int], list[int]]]
    peer_certificate: list[int] | None
    def read_chunk(self) -> bytes | None: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...

class NativeClient:
    def websocket(
        self, url: str, headers: list[tuple[bytes, bytes]], options: dict[str, Any]
    ) -> NativeWebSocket: ...
    def __init__(self, options: dict[str, Any]) -> None: ...
    def send(
        self,
        method: str,
        url: str,
        headers: list[tuple[bytes, bytes]],
        body: bytes | Iterator[bytes] | None,
        options: dict[str, Any],
    ) -> NativeResponse: ...
    def close(self) -> None: ...

class NativeCancellation:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...

class NativeWebSocket:
    status: int
    version: str
    headers: list[tuple[list[int], list[int]]]
    protocol: str | None
    def send(self, kind: str, data: bytes, code: int | None) -> None: ...
    def receive(self) -> tuple[str, list[int], int | None] | None: ...
    def cancel(self) -> None: ...
    def close(self, code: int, reason: str) -> None: ...
